# -*- coding: utf-8 -*-
"""streamlit_python.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1xy0wuMGb_PdeSyoVX4af_1nJ4KYLIVj9
"""

# app.py
import streamlit as st

# Título de la aplicación
st.title('Mi App Online con Streamlit')

# Caja de texto para que el usuario ingrese su nombre
nombre = st.text_input("¿Cómo te llamas?")

# Mostrar mensaje si el usuario ingresa su nombre
if nombre:
    st.write(f'¡Hola, {nombre}!')